### ISSUE TITLE
Support RHEL and provide rpm packages

### ISSUE THREAD

**Issue by helterskelter01** [nanoporetech/flappie#14]
Would be great to get rpm packages and a repo for RHEL7 so we can just use "yum install flappie".

regards,
Hjalti Sveinsson

**Comment by tmassingham-ont** [comment]
Hello.  We'll look at providing ready compiled packages in the future.  For the time being, it is distributed source only as fits its status as a research prototype.

**Comment by helterskelter01** [comment]
Thank you.
