### ISSUE TITLE
what about barcoding

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/flappie#15]
Dear,
i was wondering if flappie will have an option like in Albacore to de-barcode mixed run.

thanks
Luigi

**Comment by tmassingham-ont** [comment]
Hello.  Flappie isn't intended to replaced the production ONT tools and barcode demultiplexing is outside its scope.  All these niceties will be possible when the flip-flop technology is integrated into our production offerings (was Albacore, now Guppy).
