### ISSUE TITLE
Can't find cblas while trying to install dependencies via Conda

### ISSUE THREAD

**Issue by oneillkza** [nanoporetech/flappie#16]
Hi there,

I'm trying to install Flappie on an environment without root, using Conda to install the dependencies. When I try to compile Flappie, it throws the error that it can't find `cblas.h`. This file is present in the Conda environment's `/include` directory.

```
(ont_sv) [koneill@hugin flappie]$ make flappie
cd build && \
	cmake .. -DCMAKE_BUILD_TYPE=Release && \
	make
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/koneill_prj/Apps/flappie/build
make[1]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
make[2]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
make[3]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
make[3]: Leaving directory `/projects/koneill_prj/Apps/flappie/build'
make[3]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
[  5%] Building C object CMakeFiles/flappie_objects.dir/src/layers.c.o
/projects/koneill_prj/Apps/flappie/src/layers.c:12:23: error: cblas.h: No such file or directory
```

Here are the contents of the Conda environment:

```
name: ont_sv 
dependencies:
  - canu=1.8
  - sambamba=0.6.8
  - bandage=0.8.1
  - ngmlr=0.2.7
  - sniffles=1.0.10
  - nanosv=1.2.2
  - git-lfs=2.6.1
  - git=2.19.2
  - cunit=2.1.3
  - blas=1.1
  - openblas=0.3.3
  - libopenblas=0.3.3
  - hdf5=1.10.4
  - parallel=20181022
```

**Comment by oneillkza** [comment]
OK, it seems like Conda's install of libopenblas doesn't update the environment variables. The solution is to add scripts that do this on environment activation/deactivation:

https://stackoverflow.com/questions/44793143/build-program-using-library-and-headers-installed-in-a-conda-environment
https://groups.google.com/forum/#!topic/caffe-users/-B81Vy3flTA

(This is a little annoying, since it means that the Conda environment file is no longer sufficient to set up an environment that can run Flappie, but at least it gets most of the way.)

**Comment by colindaven** [comment]
Yeah, conda also interferes with Ubuntu 16.04's ability to find cblas.h. Disabling conda helped me there (not your problem, I know).

**Comment by oneillkza** [comment]
@colindaven huh, weird.

Yeah, I've kicked this whole thing over to our Systems team at our centre. In theory it should be easy to get installed, at least once there's a conda recipe. Scrappie, which seems to have very similar dependencies, installs just fine. In practice it's proven quite frustrating!

It's a little annoying that Clive Brown just decreed that everyone should switch from Albacore to Flappie without putting in the work to make Flappie easy to install.

**Comment by jts** [comment]
Clive said everyone should switch from albacore to guppy, not flappie.

**Comment by oneillkza** [comment]
It's kinda ambiguous:

https://twitter.com/i/moments/1067976367722004481

"Albacore is dead", but flappie is currently the only way to easily get hold of the up-to-date basecaller.

**Comment by oneillkza** [comment]
Thanks @jts 

Yes, it does seem to make some sense to be trying to focus on guppy, especially since it seems to be what's packaged with the "basecaller-on-board" instruments (eg PromethION).

It's still a little frustrating that guppy is only available through secret back channels at this stage, especially since we're at the point of productionising the MinION at our centre (which requires us to validate and standardise on a base caller).

**Comment by tmassingham-ont** [comment]
@jts gave a pretty good summary.  Albacore will be replaced by Guppy as the production basecaller and will be available more openly; Albacore will continue to be available but will no longer get new features.  The current versions of Albacore and Guppy are at technical parity, a future version of Guppy will include the flip-flop basecalling technique.

- _Albacore_   Depreciated production basecaller.
- _Guppy_  Production basecaller; will include flip-flop basecalling in future release.
- _Flappie_  Research prototype; preview of flip-flop basecallers.
- _Scrappie_  Research demonstrator.

_Flappie_ will, most likely, slowly replace _Scrappie_.

**Comment by liujiazhe** [comment]
> Hi there,
> 
> I'm trying to install Flappie on an environment without root, using Conda to install the dependencies. When I try to compile Flappie, it throws the error that it can't find `cblas.h`. This file is present in the Conda environment's `/include` directory.
> 
> ```
> (ont_sv) [koneill@hugin flappie]$ make flappie
> cd build && \
> 	cmake .. -DCMAKE_BUILD_TYPE=Release && \
> 	make
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /projects/koneill_prj/Apps/flappie/build
> make[1]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
> make[2]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
> make[3]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
> make[3]: Leaving directory `/projects/koneill_prj/Apps/flappie/build'
> make[3]: Entering directory `/projects/koneill_prj/Apps/flappie/build'
> [  5%] Building C object CMakeFiles/flappie_objects.dir/src/layers.c.o
> /projects/koneill_prj/Apps/flappie/src/layers.c:12:23: error: cblas.h: No such file or directory
> ```
> Here are the contents of the Conda environment:
> 
> ```
> name: ont_sv 
> dependencies:
>   - canu=1.8
>   - sambamba=0.6.8
>   - bandage=0.8.1
>   - ngmlr=0.2.7
>   - sniffles=1.0.10
>   - nanosv=1.2.2
>   - git-lfs=2.6.1
>   - git=2.19.2
>   - cunit=2.1.3
>   - blas=1.1
>   - openblas=0.3.3
>   - libopenblas=0.3.3
>   - hdf5=1.10.4
>   - parallel=20181022
> ```

hello, brother, I can not find the flappie on the conda environment, could you please uploading your commandline for me? thank you!
