### ISSUE TITLE
how do you label the raw signal sequence with nucleotides

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/flappie#26]
Hi:
    how do you label the raw signal sequence with nucleotides for training dataset?

**Comment by Psy-Fer** [comment]
Try trace_flipflop.py script.
Note, that models come from kmers, not individual nucleotides, so it isn't really that straight forward.

**Comment by huangnengCSU** [comment]
ok, thank you so much

**Comment by tmassingham-ont** [comment]
Hello.  While the signal depends on a greater region of the DNA molecule than a single nucleotide, it cannot be simply described by a kmer and the flip-flop model does not consider kmers at any point of its calculation or training.  Even so, it is important not to confuse the model a basecaller uses to represent its results with the underlying physical process that produced the signal.

The flip-flop basecaller is trained by comparing reads to a DNA sequence using techniques similar to [Connnectionist Temporal Classification](https://en.wikipedia.org/wiki/Connectionist_temporal_classification), the samples of the signal never being explicitly labelled.
If you would like a registration of the raw signal to a sequence, have a look at `squiggle` and `mappy` tools from the [Scrappie](https://github.com/nanoporetech/scrappie) package.  There is an arbitrariness in which position of the sequence each level of the signal is assigned to, we normally choose the one where the levels maximally distinguish between the assigned bases.
