### ISSUE TITLE
OpenBLAS not found

### ISSUE THREAD

**Issue by samfux84** [nanoporetech/flappie#27]
Hi,

Can you please provide the option to specify path to OpenBLAS include and library directory via cmake variable ?

I am trying to build flappie and it always fails with the error message:

```
/scratch/85150120.tmpdir/flappie/src/fast5_interface.c:336:12: warning: unused variable ‘status’ [-Wunused-variable]
     herr_t status = write_signal(read_group, res.rt.raw + res.rt.start,
            ^
[ 52%] Building C object CMakeFiles/flappie.dir/src/flappie.c.o
[ 56%] Linking C executable flappie
/usr/bin/ld: cannot find -lblas
```
Even if I set $OPENBLAS_ROOT, flappie will still try to link with -lblas

Best regards

Sam

**Comment by tmassingham-ont** [comment]
You're right, thanks.  OPENBLAS_ROOT is not being correctly passed though.  I've pushed a change to the `openblasRoot` branch.  Could you check this out please and test whether the following works please?
```bash
openblasRoot=my_openblas_root make
```

**Comment by samfux84** [comment]
@tmassingham-ont I tested it with the changes, but it still did not pick up lopenblas and tries to link against blas.

I have successfully installed flappie by changing directly the CMakeLists.txt file

**Comment by max1c** [comment]
> You're right, thanks. OPENBLAS_ROOT is not being correctly passed though. I've pushed a change to the `openblasRoot` branch. Could you check this out please and test whether the following works please?
> 
> ```shell
> openblasRoot=my_openblas_root make
> ```

Had the same issue this branch with 'openblasRoot' worked for me. Thanks for the fix.
