### ISSUE TITLE
guppy r941_5mC model ready?

### ISSUE THREAD

**Issue by avilella** [nanoporetech/flappie#28]
Flappie can be used with the guppy r941_5mC model and produces good results although requires high compute. Is the guppy r941_5mC model ready? I couldn't find '5mC guppy' search hits in the community website.

**Comment by tmassingham-ont** [comment]
Guppy does not yet support modified base calling but we are in the process of transferring this functionality into product.  The form of modified base calling we are going to release is slightly different from that release in Flappie, changing from treating 5mC as an independent fifth base to making it a dependent call.  This ‘factored’ approach has proven more powerful and is more extendable as we increase the number of modified bases we can detect.

The imminent release of Taiyaki, which supports modified bases, will contain its own GPU accelerated  base caller that is much more performant than (CPU-only) Flappie; initial benchmarks suggest it performs within a factor of 2 of Guppy.  While slower than Guppy, this caller is more flexible and we hope will enable further research and exploration of modified base calling outside the company.

**Comment by tmassingham-ont** [comment]
Released.
