### ISSUE TITLE
flappie hdf5.h error

### ISSUE THREAD

**Issue by madhubioinfo** [nanoporetech/flappie#29]
Hi I am trying to install flappie in ubuntu 18.04 and when i do make flappie i am getting the following errors , I have all my dependencies installed already
cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DHDF5_ROOT='' && \
make flappie
-- Configuring done
-- Generating done
-- Build files have been written to: /home/madhu/flappie/build
make[1]: Entering directory '/home/madhu/flappie/build'
make[2]: Entering directory '/home/madhu/flappie/build'
make[3]: Entering directory '/home/madhu/flappie/build'
make[4]: Entering directory '/home/madhu/flappie/build'
make[4]: Leaving directory '/home/madhu/flappie/build'
[ 84%] Built target flappie_objects
make[4]: Entering directory '/home/madhu/flappie/build'
make[4]: Leaving directory '/home/madhu/flappie/build'
[ 84%] Built target flappie_static
make[4]: Entering directory '/home/madhu/flappie/build'
make[4]: Leaving directory '/home/madhu/flappie/build'
make[4]: Entering directory '/home/madhu/flappie/build'
[ 84%] Building C object CMakeFiles/flappie.dir/src/fast5_interface.c.o
cc1: warning: /usr/include/hdf5/serial/hdf5.h: not a directory
In file included from /home/madhu/flappie/src/fast5_interface.c:21:0:
/home/madhu/flappie/src/fast5_interface.h:13:10: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
          ^~~~~~~~
compilation terminated.
CMakeFiles/flappie.dir/build.make:62: recipe for target 'CMakeFiles/flappie.dir/src/fast5_interface.c.o' failed
make[4]: *** [CMakeFiles/flappie.dir/src/fast5_interface.c.o] Error 1
make[4]: Leaving directory '/home/madhu/flappie/build'
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/flappie.dir/all' failed
make[3]: *** [CMakeFiles/flappie.dir/all] Error 2
make[3]: Leaving directory '/home/madhu/flappie/build'
CMakeFiles/Makefile2:153: recipe for target 'CMakeFiles/flappie.dir/rule' failed
make[2]: *** [CMakeFiles/flappie.dir/rule] Error 2
make[2]: Leaving directory '/home/madhu/flappie/build'
Makefile:223: recipe for target 'flappie' failed
make[1]: *** [flappie] Error 2
make[1]: Leaving directory '/home/madhu/flappie/build'
Makefile:30: recipe for target 'build/flappie' failed
make: *** [build/flappie] Error 2

Help me in fixing the error. Thanks in advance

**Comment by madhubioinfo** [comment]
I have reinstalled all the packages from scratch it worked !

**Comment by NguyenLePhuong** [comment]
Hi, I have the same problem with this. When you have time, could you please describe for me for about reinstall from scratch?

Thank you so much,
Kind regards,
Leo
