### ISSUE TITLE
Compilation errors:Makefile:34: recipe for target 'build/flappie' failed

### ISSUE THREAD

**Issue by jacka87164** [nanoporetech/flappie#37]
Hi flappie community,

I'm getting compilation errors when compiling on ubuntu 16.04 servers with errors. Here is the compiler output:

cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DHDF5_ROOT='' && \
make flappie
/bin/sh: 2: cmake: not found
Makefile:34: recipe for target 'build/flappie' failed
make: *** [build/flappie] Error 127

**Comment by iiSeymour** [comment]
Hi @jacka87164 

You need `cmake` to build flappie [from source](https://github.com/nanoporetech/flappie#compilation-from-source) which you can get from you systems package manager with `apt install cmake`.

**Comment by jacka87164** [comment]
Thank flappie community
I installed cmake. But the new error message is as follows:
cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DHDF5_ROOT='' && \
make flappie
-- Configuring done
-- Generating done
-- Build files have been written to: /home/flappie/build
make[1]: Entering directory '/home/flappie/build'
make[2]: Entering directory '/home/flappie/build'
make[3]: Entering directory '/home/flappie/build'
make[4]: Entering directory '/home/flappie/build'
make[4]: Leaving directory '/home/flappie/build'
make[4]: Entering directory '/home/flappie/build'
[  7%] Building C object CMakeFiles/flappie_objects.dir/src/layers.c.o
/home/flappie/src/layers.c:12:23: fatal error: cblas.h: No such file or directory
compilation terminated.
CMakeFiles/flappie_objects.dir/build.make:86: recipe for target 'CMakeFiles/flappie_objects.dir/src/layers.c.o' failed
make[4]: *** [CMakeFiles/flappie_objects.dir/src/layers.c.o] Error 1
make[4]: Leaving directory '/home/flappie/build'
CMakeFiles/Makefile2:210: recipe for target 'CMakeFiles/flappie_objects.dir/all' failed
make[3]: *** [CMakeFiles/flappie_objects.dir/all] Error 2
make[3]: Leaving directory '/home/flappie/build'
CMakeFiles/Makefile2:185: recipe for target 'CMakeFiles/flappie.dir/rule' failed
make[2]: *** [CMakeFiles/flappie.dir/rule] Error 2
make[2]: Leaving directory '/home/flappie/build'
Makefile:234: recipe for target 'flappie' failed
make[1]: *** [flappie] Error 2
make[1]: Leaving directory '/home/flappie/build'
Makefile:34: recipe for target 'build/flappie' failed
make: *** [build/flappie] Error 2

**Comment by iiSeymour** [comment]
You will need the following packages also -

```
apt install libcunit1-dev libhdf5-dev libopenblas-dev
```

**Comment by jacka87164** [comment]
I installed libcunit1-dev libhdf5-dev libopenblas-dev 
but error message:

CMakeFiles/flappie_objects.dir/build.make:110: recipe for target 'CMakeFiles/flappie_objects.dir/src/networks.c.o' failed
make[4]: *** [CMakeFiles/flappie_objects.dir/src/networks.c.o] Error 1
make[4]: Leaving directory '/home/flappie/build'
CMakeFiles/Makefile2:210: recipe for target 'CMakeFiles/flappie_objects.dir/all' failed
make[3]: *** [CMakeFiles/flappie_objects.dir/all] Error 2
make[3]: Leaving directory '/home/flappie/build'
CMakeFiles/Makefile2:185: recipe for target 'CMakeFiles/flappie.dir/rule' failed
make[2]: *** [CMakeFiles/flappie.dir/rule] Error 2
make[2]: Leaving directory '/home/flappie/build'
Makefile:234: recipe for target 'flappie' failed
make[1]: *** [flappie] Error 2
make[1]: Leaving directory '/home/flappie/build'
Makefile:34: recipe for target 'build/flappie' failed
make: *** [build/flappie] Error 2

**Comment by myrtlecat** [comment]
Do you have git-lfs installed, as mentioned in the [installation instructions](https://github.com/nanoporetech/flappie#installation)?

If git-lfs is not installed then the model files will not be cloned properly, which seems to be the case here. After installing git-lfs you will might have to delete your local copy of flappie and clone it again to get the model files.

**Comment by jacka87164** [comment]
thank you very much
