### ISSUE TITLE
minimizing memory requirement

### ISSUE THREAD

**Issue by ramcn** [nanoporetech/flappie#45]
Hello Tim,

I am looking for suggestions to minimize the memory requirement of flappie as I am trying to map it to FPGA based accelerator.

Particularly the input feature vector for each read need to be processed as a whole by the network. The size of the feature vector can range from few hundred MB to couple of GBs. depending on the size of fast5 file being processed. Is it possible to run the neural network on a fixed sliding window, overlapping the sequences on these windows and generating consensus. Similar to what for example Chiron does.

Thanks,
Ram

**Comment by tmassingham-ont** [comment]
Taken off-line.
