### ISSUE TITLE
best accuracies for direct RNA

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/flappie#49]
Do you have any direct comparison metrics for various options to basecall direct RNA runs

1) guppy with production models v.3.3.0 onwards (I think this was the last time RNA model was updated for accuracy). How stable have these models been. 

2) flappie with the version 2 flipflop model, did this one make its way into guppy production? Was from March this year
flipflop5_202003_r941rna002_ff2161d3.mdl 

3) Rerio research model released direct RNA model
res_rna2_r941_min_flipflop_v001.cfg

**Comment by tmassingham-ont** [comment]
The models in Flappie and Rerio are often  the same, Rerio being the Flappie model in a Guppy compatible form.

The only major direct comparison I am aware of is the public corona-virus data sets that were recalled and detailed in the Nanopore Community post "April accuracy update: SARS-CoV-2 and direct RNA" (reproduced in part below).  The base calls are available from https://nanoporetech.box.com/s/ggcl7vreqecjpyxrb916dbsgd35i38ih

![image](https://user-images.githubusercontent.com/19410440/85744539-e3516e80-b6fc-11ea-80e7-6c5e2d8f88db.png)

**Comment by callumparr** [comment]
I see. So the 'standard' hac model for RNA is the same between 3.5.1 to the latest 4.0.11? 

So I would expect some boost in accuracy if using rerio model in guppy compared to data I originally basecalled with guppy v3.4.5?

**Comment by tmassingham-ont** [comment]
The status of the models in Guppy would be better directed to its developers; I don't know the full details and wouldn't want to mislead you.  
You should see a significant improvement in accuracy between Guppy v3.4.5 and the Rerio RNA model; all the sets I have tested with showed ~1.5% improvement over Guppy v3.5.1 and these covered both native and synthetic RNA strands.

**Comment by callumparr** [comment]
Thank you sounds great.
